######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	network_support

AFILES= 	autodoc.asm

CFILES= 

OFILES= 

all quick:
	 	touch ${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
