######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	rexx_support

AFILES=		autodoc.asm

OFILES= 	rexxvars.o

all quick:	${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
