######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	timer_support

AFILES= 	TimeDelay.asm

OFILES= 	TimeDelay.obj

all quick:	${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
