######################################################################
MAKEMETA=	../../tools/makemeta

SUBSYSNAME=	hardware

AFILES=		cia.asm custom.asm memmap.asm

OFILES= 	cia.obj custom.obj memmap.obj

all quick:	${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
