######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	commodities_support

AFILES= 	autodocs.asm

CFILES= 

OFILES= 

all quick:
	 	touch ${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
