######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	graphics_support

AFILES=

CFILES=

OFILES=

all quick:
		touch ${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
