######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	clib

AFILES= 	doprnt.asm ga.asm intmath.asm random.asm rt.asm sprintf.asm \
		autodocs.asm

CFILES= 	fclose.c fgetc.c fprintf.c fputc.c fputs.c \
		g.c getchar.c printf.c putchar.c puts.c

OFILES= 	doprnt.obj ga.obj intmath.obj random.obj rt.obj sprintf.obj \
		fclose.obj fgetc.obj fprintf.obj fputc.obj fputs.obj \
		g.obj getchar.obj printf.obj putchar.obj puts.obj

all quick:	${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
