######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	intuition_support

AFILES= 	autodocs.asm hookface.asm classface.asm

CFILES= 

OFILES=		hookface.obj classface.obj

all quick:	${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
