######################################################################
MAKEMETA=	../../../tools/makemeta

SUBSYSNAME=	dos_support

AFILES= 	namefromanchor.asm

CFILES= 	

OFILES= 	namefromanchor.obj

all quick:	${SUBSYSNAME}_lib.lib

.INCLUDE=${MAKEMETA}
