#include	<clib/alib_protos.h>
#include	<clib/alib_stdio_protos.h>
#include	<clib/asl_protos.h>
#include	<clib/battclock_protos.h>
#include	<clib/battmem_protos.h>
#include	<clib/cia_protos.h>
#include	<clib/commodities_protos.h>
#include	<clib/console_protos.h>
#include	<clib/diskfont_protos.h>
#include	<clib/dos_protos.h>
#include	<clib/exec_protos.h>
#include	<clib/expansion_protos.h>
#include	<clib/gadtools_protos.h>
#include	<clib/graphics_protos.h>
#include	<clib/icon_protos.h>
#include	<clib/iffparse_protos.h>
#include	<clib/input_protos.h>
#include	<clib/intuition_protos.h>
#include	<clib/keymap_protos.h>
#include	<clib/layers_protos.h>
#include	<clib/macros.h>
#include	<clib/mathffp_protos.h>
#include	<clib/mathieeedoubbas_protos.h>
#include	<clib/mathieeedoubtrans_protos.h>
#include	<clib/mathieeesingbas_protos.h>
#include	<clib/mathieeesingtrans_protos.h>
#include	<clib/mathtrans_protos.h>
#include	<clib/misc_protos.h>
#include	<clib/potgo_protos.h>
#include	<clib/ramdrive_protos.h>
#include	<clib/timer_protos.h>
#include	<clib/translator_protos.h>
#include	<clib/utility_protos.h>
#include	<clib/wb_protos.h>
