#ifndef PROTO_ALL_H
#define PROTO_ALL_H
#include <exec/types.h>

#include <proto/asl.h>
#include <proto/battclock.h>
#include <proto/battmem.h>
#include <proto/cia.h>
#include <proto/commodities.h>
#include <proto/console.h>
#include <proto/diskfont.h>
#include <proto/dos.h>
#include <proto/exec.h>
#include <proto/expansion.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/icon.h>
#include <proto/iffparse.h>
#include <proto/input.h>
#include <proto/intuition.h>
#include <proto/keymap.h>
#include <proto/layers.h>
#include <proto/mathffp.h>
#include <proto/mathieeedoubbas.h>
#include <proto/mathieeedoubtrans.h>
#include <proto/mathieeesingbas.h>
#include <proto/mathieeesingtrans.h>
#include <proto/mathtrans.h>
#include <proto/misc.h>
#include <proto/potgo.h>
#include <proto/ramdrive.h>
#include <proto/timer.h>
#include <proto/translator.h>
#include <proto/utility.h>
#include <proto/wb.h>
#endif
