
all:	DCC DCPP DC1 DAS DLINK DMAKE DOBJ DUTIL UPREV

DCC:
	(cd dcc; make)

DCPP:
	(cd dcpp; make)

DC1:
	(cd dc1; make)

DAS:
	(cd das; make)

DLINK:
	(cd dlink; make)

DMAKE:
	(cd dmake; make)

DOBJ:
	(cd dobj; make)

DUTIL:
	(cd dutil; make)

UPREV:
	(cd uprev; make)

install:
	(cd dcc; make install)
	(cd dcpp; make install)
	(cd dc1; make install)
	(cd das; make install)
	(cd dlink; make install)
	(cd dmake; make install)
	(cd dobj; make install)
	(cd dutil; make install)
	(cd uprev; make install)

clean:
	(cd dcc; make clean)
	(cd dcpp; make clean)
	(cd dc1; make clean)
	(cd das; make clean)
	(cd dlink; make clean)
	(cd dmake; make clean)
	(cd dobj; make clean)
	(cd dutil; make clean)
	(cd uprev; make clean)

.PHONY: DCC DCPP DC1 DAS DLINK DMAKE DOBJ DUTIL UPREV clean install
